### ISSUE TITLE
App crashes after the initial login

### ISSUE THREAD

**Issue by wanclem** [Raiinmaker/tiktok_login_flutter#8]
**Issue Description:**

The application crashes immediately after the initial submission, displaying the following error message:

```java 
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lingomate.cc/com.raiinmaker.tiktok_login_flutter.tiktokapi.TikTokEntryActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(18201): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
E/AndroidRuntime(18201): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
E/AndroidRuntime(18201): at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
```

**Additional Information:**

- The error seems to be originating from the `TikTokEntryActivity` class.
- The specific issue appears to be an `IllegalStateException` indicating that a reply has already been submitted.
- This issue prevents the app from functioning properly after the initial submission.

**Comment by urvashi-k-7span** [comment]
Any update on this?
